# Generated by Django 3.0.3 on 2020-02-15 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=None, max_length=50)),
                ('lastName', models.CharField(default=None, max_length=50)),
                ('middleInitial', models.CharField(default=None, max_length=1)),
                ('homePhone', models.CharField(blank=True, max_length=13, null=True)),
                ('mobilePhone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=None)),
                ('address1', models.CharField(default=None, max_length=50)),
                ('address2', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('userID', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(default=None, max_length=50)),
                ('indoor', models.BooleanField(default=True, verbose_name='Y')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('startTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('field', models.IntegerField(blank=True, null=True)),
                ('homeTeamID', models.IntegerField(blank=True, null=True)),
                ('homeTeamScore', models.IntegerField(blank=True, null=True)),
                ('awayTeamID', models.IntegerField(blank=True, null=True)),
                ('awayTeamScore', models.IntegerField(blank=True, null=True)),
                ('officialContact', models.IntegerField(blank=True, null=True)),
                ('tournamentID', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leagueName', models.CharField(default=None, max_length=50)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(default=None, max_length=50)),
                ('locationContactID', models.IntegerField(blank=True, null=True)),
                ('address1', models.CharField(default=None, max_length=50)),
                ('address2', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('zipcode', models.CharField(default=None, max_length=50)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(default=None, max_length=50)),
                ('coach', models.IntegerField(blank=True, null=True)),
                ('league', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('startDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentHasLeagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentID', models.IntegerField(blank=True, null=True)),
                ('leagueID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=None, max_length=50)),
                ('tournamentID', models.IntegerField(blank=True, null=True)),
                ('contactID', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
