# Generated by Django 3.0.3 on 2020-02-15 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('startTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('homeTeamID', models.CharField(default=None, max_length=50)),
                ('homeTeamScore', models.IntegerField(blank=True, null=True)),
                ('awayTeamID', models.CharField(default=None, max_length=50)),
                ('awayTeamScore', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lastModifiedBy', models.CharField(default=None, max_length=50)),
                ('lastModifiedDate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('field', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Field')),
            ],
        ),
        migrations.RenameModel(
            old_name='Leagues',
            new_name='League',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='TournamentHasLeagues',
            new_name='TournamentHasLeague',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Location'),
        ),
        migrations.AddField(
            model_name='game',
            name='officialContact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Contact'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournamentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Tournament'),
        ),
    ]
