# Generated by Django 3.0.3 on 2020-02-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_auto_20200215_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='userID',
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.League'),
        ),
        migrations.AlterField(
            model_name='tournamenthasleague',
            name='leagueID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.League'),
        ),
        migrations.AlterField(
            model_name='tournamenthasleague',
            name='tournamentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Tournament'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contactID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.Contact'),
        ),
    ]
