# Generated by Django 3.0.3 on 2020-02-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_auto_20200215_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamenthasleague',
            name='leagueID',
        ),
        migrations.RemoveField(
            model_name='tournamenthasleague',
            name='tournamentID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contactID',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field',
        ),
        migrations.RemoveField(
            model_name='game',
            name='officialContact',
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='soccer.League'),
        ),
        migrations.AddField(
            model_name='location',
            name='FieldNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='indoor',
            field=models.BooleanField(default=True, verbose_name='Y'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='TournamentHasLeague',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
